.TH KB 1
.SH NAME
kb \-
.SM MIDI
keyboard daemon for
.SM JACK
.
.SH SYNOPSIS
.B kb
.RB [ \-ah ]
.RB [ \-c
.IR channel ]
.
.SH DESCRIPTION
.B kb
is a customizable virtual
.SM MIDI
keyboard daemon for
.SM JACK
Audio Connection Kit.
It provides
.SM MIDI
input for standalone
.SM JACK
synthesizers and can be a useful debugging tool for developing \s-1JACK\s0-based
audio applications.
.
.PP
To use
.BR kb ,
first start a
.SM JACK
server using
.B jackd(1)
or
.BR qjackctl(1) .
Then run
.PP
.in +4n
.EX
$ \fBkb\fP
.EE
.in
.PP
to start the
.SM MIDI
keyboard daemon.
.
Connect the
.B midi_out
port of
.B kb
to other applications (for
.BR qjackctl(1) ,
use the
.I Graph
button):
.PP
.in +4n
.EX
+----+-----------+       +-------+-----------+
| kb |           |       | synth |           |
+----+           |       +-------+           |
|                |       |         audio_out +--->
|       midi_out +------>+ midi_in           |
+----------------+       +-------------------+
.EE
.in
.PP
Alternatively, use the
.B \-a
option to let
.B kb
automatically detect and connect to input MIDI ports:
.PP
.in +4n
.EX
$ \fBkb\fP -a
.EE
.in
.PP
.B kb
will capture all the key presses and convert them into
.SM MIDI
messages according to your configuration.
.
.PP
If you compiled with default configuration, the home row of a QWERTY keyboard
.PP
.in +4n
.EX
ASDFGHJKL;'
.EE
.in
.PP
corresponds to the white keys on a piano keyboard, and
.PP
.in +4n
.EX
WETYUOP]
.EE
.in
.PP
corresponds to the black keys.
Additionally,
.BR ZX ", " CV ", " 90 ,
and
.B \-=
can be used to decrement and increment
.BR octave ", " velocity ", " bank ,
and
.BR program ,
respectively.
And the
.B Escape
key is the
.B panic
button (turn off all notes).
However, because
.B kb
can be easily customized, the keybindings of your
.B kb
might be different.
.
.PP
If you want to shut down the daemon, press
.B Ctrl-C
in the terminal to send a
.B SIGINT
signal or run
.PP
.in +4n
.EX
$ pkill kb
.EE
.in
.PP
to kill the daemon process.
.
.SH OPTIONS
.TP
.B \-h
Print usage and exit.
.TP
.B \-a
If set, automatically detect and connect to any input
.SM MIDI
ports available.
.TP
.BI \-c " channel"
Set the output
.SM MIDI
channel.
Must be between
.B 1
to
.BR 16 ,
inclusive.
The default is
.BR 1 .
.
. SH CAVEATS
Note that
.B kb
.I captures
your key presses in any window.
It does not
.I intercept
them.
This is intentional, because I frequently need to edit code while testing
the MIDI input.
As an additional benefit, you can now enjoy some crappy generative music while
typing.
